sets.exported={
    head={ name="Herculean Helm", augments={'INT+5','STR+2','Phalanx +3','Accuracy+20 Attack+20','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    item="Miso Ramen",
    item="Silver Voucher",
    item="Tropical Crepe",
    item="Kindred's Crest",
    left_ring="Echad Ring",
    left_ring="Trizek Ring",
    left_ring="Warp Ring",
    item="Panacea",
    sub={ name="Guttler", augments={'DMG:+7',}},
    ammo="Living Bullet",
    item="Vile Elixir +1",
    item="Remedy",
    item="Holy Water",
    left_ring="Dim. Ring (Dem)",
    item="Trump Card",
    item="Trump Card Case",
    item="Echo Drops",
    item="Shihei",
    item="Vile Elixir",
    item="H-P Bayld",
    item="H. Kindred Crest",
    item="El. Pachira Fruit",
    item="Abdhaljs Seal",
    item="Maze Tabula R01",
    waist={ name="Tellen Belt", augments={'Path: A',}},
    ammo="Chrono Bullet",
    item="S. Kindred Crest",
    item="Hi-Reraiser",
    item="SP Gobbie Key",
    item="Forbidden Key",
    item="Mars Orb",
    item="Copper Voucher",
    item="Lustreless Wing",
    ammo="Devastating Bullet",
    ammo="Living Bullet",
    item="S. Astral Detritus",
    item="Pluton",
    item="Linkpearl",
    item="Venus Orb",
    item="Reraiser",
    item="Antacid",
    item="L. Wing Box",
    item="Prism Powder",
    item="Grape Daifuku",
    item="Ctrice. Tailmeat",
    item="Rolan. Daifuku",
    item="Smooth Whisker",
    item="Pluton Box",
    ammo="Dire Broth",
    item="Durium Sheet",
    item="Dial Key #Fo",
    item="Beitetsu",
    item="Resilient Mane",
    item="Eft Blood",
    item="Ocl. Sheet",
    item="Pluton Case",
    item="Rem's Tale Ch.8",
    item="Boulder Box",
    item="Alexandrite",
    back={ name="Artio's Mantle", augments={'Pet: M.Acc.+20 Pet: M.Dmg.+20','Eva.+20 /Mag. Eva.+20','Pet: Mag. Acc.+10','"Fast Cast"+10','Phys. dmg. taken-10%',}},
    item="Damascus Ingot",
    item="Riftborn Boulder",
    item="Old Case",
    item="Gil",
    item="Ceramic Flowerpot",
    item="Earth Crystal",
    item="Lightng. Crystal",
    item="Tarutaru Rice",
    item="Grain Seeds",
    item="Vana'clock",
    item="Tarutaru Rice",
    item="Prishe Statue",
    body="Poroggo Fleece +1",
    item="Gilded Shelf",
    head="Guide Beret",
    body="Mithra Top +1",
    hands="Pill. Armlets +1",
    item="Gilded Shelf",
    hands="Karagoz Guanti +1",
    legs="Meg. Chausses +2",
    feet="Atrophy Boots +1",
    item="Tarutaru Rice",
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    sub="Ternion Dagger",
    ammo="Hydrocera",
    head={ name="Herculean Helm", augments={'Attack+18','Accuracy+16','Quadruple Attack +2','Mag. Acc.+12 "Mag.Atk.Bns."+12',}},
    head="Chironic Hat",
    body={ name="Herculean Vest", augments={'"Mag.Atk.Bns."+26','Pet: Attack+20 Pet: Rng.Atk.+20','Accuracy+8 Attack+8','Mag. Acc.+13 "Mag.Atk.Bns."+13',}},
    body={ name="Herculean Vest", augments={'"Mag.Atk.Bns."+22','Magic burst dmg.+4%','INT+5','Mag. Acc.+15',}},
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','Magic burst dmg.+10%','INT+1','Mag. Acc.+1','"Mag.Atk.Bns."+11',}},
    hands={ name="Herculean Gloves", augments={'"Store TP"+4','MND+13','Phalanx +4',}},
    hands="Chironic Gloves",
    legs="Herculean Trousers",
    legs={ name="Herculean Trousers", augments={'"Mag.Atk.Bns."+25','Phys. dmg. taken -4%','INT+7',}},
    legs="Herculean Trousers",
    legs="Herculean Trousers",
    legs={ name="Herculean Trousers", augments={'Pet: Accuracy+23 Pet: Rng. Acc.+23','Pet: "Dbl. Atk."+3','Pet: DEX+10','Pet: Attack+15 Pet: Rng.Atk.+15',}},
    feet="Hippo. Socks +1",
    legs="Chironic Hose",
    feet={ name="Herculean Boots", augments={'Mag. crit. hit dmg. +3%','Attack+3','Phalanx +4',}},
    feet={ name="Merlinic Crackows", augments={'MND+10','Accuracy+4','Phalanx +3',}},
    feet={ name="Herculean Boots", augments={'Accuracy+21','Weapon skill damage +4%','DEX+8',}},
    waist="Shinjutsu-no-Obi",
    main="Gnafron's Adargas",
    ammo="Fizzy Broth",
    ammo="Blackwater Broth",
    ammo="Dire Broth",
    ammo="Putrescent Broth",
    head="Skormoth Mask",
    waist="Chaac Belt",
    left_ring="Rajas Ring",
    sub={ name="Iris", augments={'Blue Magic skill +15','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    main="Crepuscular Scythe",
    sub={ name="Acrontica", augments={'Path: A',}},
    main="Grioavolr",
    sub={ name="Arktoi", augments={'Accuracy+50','Pet: Accuracy+50','Pet: Attack+30',}},
    waist="Siegel Sash",
    sub={ name="Iris", augments={'Blue Magic skill +15','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    back={ name="Mecisto. Mantle", augments={'Cap. Point+50%','STR+2','DEF+5',}},
    ammo="Pet Food Theta",
    ammo="Livid Broth",
    ammo="Pet Food Theta",
    ammo="Spicy Broth",
    neck="Unmoving Collar",
    ammo="Aged Humus",
    sub="Mes'yohi Rod",
    ammo="C. Plasma Broth",
    range="Troll Gun",
    ammo="Meaty Broth",
    back="Cornflower Cape",
    sub="Adapa Shield",
    item="Sobek's Skin",
    sub="Utu Grip",
    item="El. Pachira Fruit",
    ammo="C. Plasma Broth",
    item="El. Pachira Fruit",
    ammo="Automat. Oil +3",
    left_ring="Supershear Ring",
    ammo="Bubbly Broth",
    legs="Esthete's Hose",
    body="Esthete's Coat",
    left_ear="Terminus Earring",
    head={ name="Merlinic Hood", augments={'"Mag.Atk.Bns."+10','STR+5','Phalanx +4','Mag. Acc.+4 "Mag.Atk.Bns."+4',}},
    item="Sarameya's Hide",
    legs={ name="Merlinic Shalwar", augments={'STR+10','Blood Pact Dmg.+4','Phalanx +4','Mag. Acc.+13 "Mag.Atk.Bns."+13',}},
    item="2Lf. Chloris Bud",
    back="Canny Cape",
    back="Yokaze Mantle",
    hands="Kurys Gloves",
    back="Gunslinger's Cape",
    neck="Maskirova Torque",
    ammo="Knobkierrie",
    neck="Sacro Gorget",
    feet="Ahosi Leggings",
    ammo="Hasty Pinion +1",
    ammo="Automat. Oil +3",
    ammo="Automat. Oil +3",
    item="Crystal Petrifact",
    item="Crystal Petrifact",
    item="Crystal Petrifact",
    body="Councilor's Garb",
    feet="Inspirited Boots",
    sub="Ark Shield",
    item="Pursuer's Wing",
    head="Esthete's Masque",
    ammo="Gassy Sap",
    item="Jaculus Wing",
    body={ name="Merlinic Jubbah", augments={'"Store TP"+3','Accuracy+26','Phalanx +4','Mag. Acc.+10 "Mag.Atk.Bns."+10',}},
    hands="Councilor's Cuffs",
    body="Hjarrandi Breast.",
    sub="Heishi Shorinken",
    feet="Estq. Houseaux",
    ammo="Spumante Broth",
    main="Opashoro",
    item="Befouled Water",
    ammo="Venomous Broth",
    ammo="Vis. Broth",
    sub="Kustawi +1",
    waist="Cornelia's Belt",
    main="Dojikiri Yasutsuna",
    hands={ name="Merlinic Dastanas", augments={'INT+14','"Store TP"+4','Phalanx +3',}},
    left_ear={ name="Bhikku Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+12','Mag. Acc.+12','"Store TP"+4',}},
    item="Storage Slip 03",
    item="Storage Slip 23",
    item="Mog Pell (Red)",
    item="Maat's Mix",
    item="Mog Pell (Silver)",
    back="Nexus Cape",
    item="A. Vou.: Hands +1",
    item="Faithfl. Torso IV",
    item="Crystal Petrifact",
    item="A. Vou.: Head +1",
    item="Storage Slip 24",
    item="Li. Gr. Coffer",
    item="Tr. Gr. Coffer",
    item="A. Vou.: Fingers",
    item="Storage Slip 08",
    item="Storage Slip 21",
    item="Kupon A-ASYW",
    item="Storage Slip 04",
    item="A. Tok.: Head +1",
    item="A. Tok.: Feet +1",
    item="A. Tok.: Body +1",
    item="Abdhaljs Matter",
    item="Abdhaljs Anima",
    item="Storage Slip 15",
    item="Abdhaljs Fiber",
    item="A. Vou.: Legs +1",
    item="Storage Slip 16",
    item="Atst. of Might",
    item="Storage Slip 06",
    item="Abdhaljs Metal",
    item="Abdhaljs Seal",
    main="Autarch's Axe",
    item="Storage Slip 19",
    item="A. Vou.: Feet +1",
    item="Abdhaljs Gem",
    item="Atst. of Vigor",
    item="A. Vou.: Body +1",
    feet="Iga Kyahan",
    item="Sadist's Fortune",
    item="A. Voucher: Back",
    item="Abdhaljs Nugget",
    item="Deluder's Fortune",
    item="Storage Slip 17",
    item="Atst. of Transcen.",
    item="Du. Gr. Coffer",
    item="A. Tok.: Hands +1",
    item="Ig. Gr. Coffer",
    item="Abdhaljs Resin",
    item="Despot's Fortune",
    item="A. Tok.: Legs +1",
    item="Gr. Gr. Coffer",
    item="A. Voucher: Weapon",
    item="Abdhaljs Sap",
    item="Ym. Gr. Coffer",
    item="Atst. of Harmony",
    item="Faithful's Legs IV",
    item="Abdhaljs Dye",
    item="Diligence Grimoire",
    item="Yorcia Visage I",
    item="Abdhaljs Dust",
    item="Eudaemon Sash",
    item="Old Case",
    main="Reikikon",
    item="Old Case",
    item="Old Case",
    item="Mog Pell (Green)",
    item="Abdhaljs Dust",
    item="Abdhaljs Thread",
    item="Coin of Glory",
    item="Abdhaljs Thread",
    item="Ancient Lumber",
    item="Maat's Concoc.",
    item="Tinnin's Fang",
    item="Fu's Scale",
    item="P. SCH Card",
    item="Kin's Scale",
    item="Kei's Scale",
    item="P. DNC Card",
    item="P. PUP Card",
    item="P. THF Card",
    item="Kyou's Scale",
    item="P. GEO Card",
    item="Handshard: MNK",
    item="P. WHM Card",
    item="Coin of Adv.",
    item="Eikondrite",
    item="Coin of Decay",
    item="Coin of Ruin",
    item="Gin's Scale",
    item="P. BST Card",
    item="Headshard: RDM",
    item="P. COR Card",
    item="Ra'Kaz. Sapphire",
    item="P. MNK Card",
    item="P. PUP Card",
    item="P. COR Card",
    item="Voidfoot: BLM",
    item="Isgebind's Heart",
    item="Torsoshard: GEO",
    item="Cirein. Lantern",
    item="Kupon I-Seal",
    item="Voidtorso: BLU",
    item="Tr.Abjuration: Hd.",
    item="Bukhis's Wing",
    item="P. BLM Card",
    item="Frayed Pouch (A)",
    item="Voidtorso: BST",
    item="Azdaja's Horn",
    item="Voidhand: BLU",
    item="P. BLU Card",
    item="Cirdas Visage IV",
    item="Ra'Kaz. Starstone",
    item="Frayed Pouch (D)",
    item="Frayed Pouch (R)",
    item="Legshard: BLU",
    item="P. PUP Card",
    item="P. PUP Card",
    item="Torsoshard: BST",
    item="Voidhead: BLU",
    item="Torsoshard: BLU",
    item="Voidfoot: BST",
    item="Headshard: BLU",
    item="P. BRD Card",
    item="Mog Pell (Silver)",
    left_ear={ name="Hattori Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+11','Mag. Acc.+11','"Store TP"+3',}},
    item="Frayed Pouch (B)",
    item="Moonbow Leather",
    item="Dial Key #Ab",
    item="Moonbow Steel",
    ammo="Pet Food Theta",
    item="Frayed Pouch (G)",
    item="Waktza Crest",
    ammo="Pet Food Theta",
    back="Lifestream Cape",
    item="Moonbow Cloth",
    item="Frayed Sack (D)",
    item="Frayed Sack (L)",
    item="C. Ice Shard",
    neck="Debilis Medallion",
    head="Acad. Mortar. +3",
    main={ name="Ohtas", augments={'Accuracy+70','Pet: Accuracy+70','Pet: Haste+10%',}},
    left_ear="Meili Earring",
    body="Acad. Gown +3",
    head="Ebers Cap +1",
    waist={ name="Acuity Belt +1", augments={'Path: A',}},
    legs="Jhakri Slops +2",
    hands="Acad. Bracers +3",
    left_ring="Mallquis Ring",
    body="Maxixi Casaque +3",
    legs="Acad. Pants +3",
    head={ name="Rao Kabuto +1", augments={'Pet: HP+125','Pet: Accuracy+20','Pet: Damage taken -4%',}},
    body="Ebers Bliaut +3",
    waist="Incarnation Sash",
    body="Jhakri Robe +2",
    sub={ name="Terpsichore", augments={'Path: A',}},
    hands="Jhakri Cuffs +2",
    left_ring="Menelaus's Ring",
    legs={ name="Pitre Churidars +3", augments={'Enhances "Ventriloquy" effect',}},
    left_ring="Shiva Ring +1",
    hands={ name="Rao Kote +1", augments={'Pet: HP+125','Pet: Accuracy+20','Pet: Damage taken -4%',}},
    legs="Ebers Pant. +3",
    feet="Acad. Loafers +3",
    feet={ name="Pitre Babouches +3", augments={'Enhances "Role Reversal" effect',}},
    head={ name="Taeon Chapeau", augments={'Pet: Accuracy+23 Pet: Rng. Acc.+23','Pet: "Dbl. Atk."+5','Pet: Damage taken -4%',}},
    head={ name="Peda. M.Board +3", augments={'Enh. "Altruism" and "Focalization"',}},
    head="C. Palug Crown",
    legs={ name="Horos Tights +3", augments={'Enhances "Saber Dance" effect',}},
    head="Jhakri Coronal +2",
    back={ name="Dispersal Mantle", augments={'STR+4','DEX+2','Pet: TP Bonus+480','"Martial Arts"+11',}},
    neck="Shulmanu Collar",
    legs={ name="Rao Haidate +1", augments={'Pet: HP+125','Pet: Accuracy+20','Pet: Damage taken -4%',}},
    main="Chatoyant Staff",
    feet={ name="Rao Sune-Ate +1", augments={'Pet: HP+125','Pet: Accuracy+20','Pet: Damage taken -4%',}},
    waist="Bishop's Sash",
    body={ name="Pitre Tobe +3", augments={'Enhances "Overdrive" effect',}},
    left_ear="Beatific Earring",
    hands={ name="Herculean Gloves", augments={'"Fast Cast"+3','Pet: Mag. Acc.+23 Pet: "Mag.Atk.Bns."+23','STR+3 DEX+3','Accuracy+18 Attack+18','Mag. Acc.+1 "Mag.Atk.Bns."+1',}},
    sub="Daybreak",
    head={ name="Pitre Taj +3", augments={'Enhances "Optimization" effect',}},
    neck={ name="Argute Stole +2", augments={'Path: A',}},
    body={ name="Taeon Tabard", augments={'Pet: Accuracy+21 Pet: Rng. Acc.+21','Pet: "Dbl. Atk."+5','Pet: Damage taken -4%',}},
    neck="Bfn. Collar +1",
    left_ear={ name="Handler's Earring +1", augments={'Path: A',}},
    body={ name="Peda. Gown +3", augments={'Enhances "Enlightenment" effect',}},
    head={ name="Herculean Helm", augments={'Pet: Mag. Acc.+29','Pet: INT+1','Pet: Attack+8 Pet: Rng.Atk.+8','Pet: "Mag.Atk.Bns."+15',}},
    main="Malignance Pole",
    range="Animator P II",
    hands={ name="Peda. Bracers +3", augments={'Enh. "Tranquility" and "Equanimity"',}},
    legs={ name="Taeon Tights", augments={'Pet: Accuracy+23 Pet: Rng. Acc.+23','Pet: "Dbl. Atk."+5','Pet: Damage taken -4%',}},
    sub={ name="Gleti's Knife", augments={'Path: A',}},
    left_ring="Thur. Ring +1",
    head={ name="Herculean Helm", augments={'"Store TP"+1','Magic Damage +1','"Treasure Hunter"+2','Accuracy+7 Attack+7',}},
    legs={ name="Peda. Pants +3", augments={'Enhances "Tabula Rasa" effect',}},
    feet="Hermes' Sandals",
    waist="Klouskap Sash +1",
    left_ear="Mimir Earring",
    back={ name="Bookworm's Cape", augments={'INT+1','MND+2','Helix eff. dur. +20','"Regen" potency+10',}},
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    hands="Ebers Mitts +3",
    feet={ name="Horos T. Shoes +3", augments={'Enhances "Closed Position" effect',}},
    sub="Ammurapi Shield",
    head={ name="Vanya Hood", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    feet={ name="Peda. Loafers +3", augments={'Enhances "Stormsurge" effect',}},
    feet="Ebers Duckbills +3",
    head={ name="Literae Hat", augments={'"Conserve MP"+1','Dark magic skill +4','INT+1 MND-0.5 CHR-0.5',}},
    neck="Erra Pendant",
    neck={ name="Pup. Collar +2", augments={'Path: A',}},
    waist="Grunfeld Rope",
    head="Maxixi Tiara +3",
    feet="Herald's Gaiters",
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    back={ name="Fi Follet Cape +1", augments={'Path: A',}},
    waist="Isa Belt",
    feet={ name="Vanya Clogs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    left_ring="Kishar Ring",
    left_ring="Ilabrat Ring",
    sub={ name="Malevolence", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+10','"Fast Cast"+5',}},
    waist="Sacro Cord",
    item="Dawn Mulsum",
    item="Dawn Mulsum",
    item="Dawn Mulsum",
    item="Dawn Mulsum",
    left_ring="Locus Ring",
    item="Dawn Mulsum",
    item="Dawn Mulsum",
    item="Dawn Mulsum",
    hands={ name="Herculean Gloves", augments={'AGI+9','"Mag.Atk.Bns."+25','Accuracy+18 Attack+18','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    sub="Bloodrain Strap",
    neck="Carnal Torque",
    legs={ name="Lustr. Subligar +1", augments={'Accuracy+20','DEX+8','Crit. hit rate+3%',}},
    neck="Empath Necklace",
    left_ear="Tripudio Earring",
    waist="Shetal Stone",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    legs="Th. Pant. +3",
    head={ name="Merlinic Hood", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','Magic burst dmg.+10%','INT+5','Mag. Acc.+3','"Mag.Atk.Bns."+9',}},
    neck="Anu Torque",
    hands="Malignance Gloves",
    feet={ name="Lustra. Leggings +1", augments={'HP+65','STR+15','DEX+15',}},
    main={ name="Tupsimati", augments={'Path: A',}},
    left_ring="Lebeche Ring",
    sub="Maxentius",
    head="Arbatel Bonnet +3",
    sub="Genmei Shield",
    left_ring="Freke Ring",
    waist="Skrymir Cord +1",
    head={ name="Nyame Helm", augments={'Path: B',}},
    legs="Malignance Tights",
    hands="Arbatel Bracers +3",
    left_ring="Stikini Ring +1",
    sub="Tauret",
    sub={ name="Machaera +2", augments={'TP Bonus +1000',}},
    main={ name="Xiucoatl", augments={'Path: C',}},
    left_ring="Chirich Ring +1",
    ammo="Pemphredo Tathlum",
    feet="Theo. Duckbills +3",
    main={ name="Marin Staff +1", augments={'Path: A',}},
    hands={ name="Merlinic Dastanas", augments={'"Mag.Atk.Bns."+11','"Drain" and "Aspir" potency +10','MND+6',}},
    left_ring="Haoma's Ring",
    body="Theo. Bliaut +2",
    waist="Oneiros Rope",
    main={ name="Midnights", augments={'Pet: Attack+25','Pet: Accuracy+25','Pet: Damage taken -3%',}},
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+21 "Mag.Atk.Bns."+21','Magic burst dmg.+11%','Mag. Acc.+11','"Mag.Atk.Bns."+13',}},
    body={ name="Nyame Mail", augments={'Path: B',}},
    left_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    waist="Carrier's Sash",
    hands="Theophany Mitts +2",
    body={ name="Piety Bliaut +3", augments={'Enhances "Benediction" effect',}},
    hands={ name="Nyame Gauntlets", augments={'Path: B',}},
    left_ear="Malignance Earring",
    head="Malignance Chapeau",
    sub="Culminus",
    legs={ name="Piety Pantaln. +3", augments={'Enhances "Afflatus Misery" effect',}},
    legs={ name="Nyame Flanchard", augments={'Path: B',}},
    legs="Perdition Slops",
    sub="Heartbeater",
    waist="Embla Sash",
    head="Maculele Tiara +3",
    legs="Heyoka Subligar +1",
    sub="Yagrush",
    ammo="C. Palug Stone",
    left_ear="Enmerkar Earring",
    ammo="Floestone",
    neck="Lissome Necklace",
    head="Befouled Crown",
    head="Inyanga Tiara +2",
    left_ear="Telos Earring",
    head={ name="Piety Cap +3", augments={'Enhances "Devotion" effect',}},
    body="Inyanga Jubbah +2",
    hands="Inyan. Dastanas +2",
    hands="Regal Cuffs",
    feet="Foire Babouches +3",
    left_ear="Dedition Earring",
    hands="Maxixi Bangles +3",
    hands="Foire Dastanas +2",
    neck="Fotia Gorget",
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    body={ name="Adhemar Jacket +1", augments={'STR+12','DEX+12','Attack+20',}},
    back="Oretan. Cape +1",
    legs="Inyanga Shalwar +2",
    back={ name="Senuna's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    back={ name="Visucius's Mantle", augments={'Pet: M.Acc.+20 Pet: M.Dmg.+20','Pet: Magic Damage+10','Pet: "Regen"+10','Pet: "Regen"+5',}},
    left_ear="Suppanomimi",
    feet="Inyan. Crackows +2",
    body={ name="Rao Togi +1", augments={'Pet: HP+125','Pet: Accuracy+20','Pet: Damage taken -4%',}},
    hands={ name="Piety Mitts +3", augments={'Enhances "Martyr" effect',}},
    waist="Fotia Belt",
    sub="Beneficus",
    body="Twilight Cloak",
    body="Lethargy Sayon +3",
    feet={ name="Piety Duckbills +3", augments={'Enhances "Afflatus Solace" effect',}},
    feet="Malignance Boots",
    back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    left_ear="Regal Earring",
    range="Animator P +1",
    sub={ name="Magesmasher +1", augments={'Path: A',}},
    waist={ name="Kentarch Belt +1", augments={'Path: A',}},
    main="Lost Sickle",
    head={ name="Telchine Cap", augments={'Enh. Mag. eff. dur. +10',}},
    sub="Aeneas",
    sub="Khonsu",
    ammo={ name="Ghastly Tathlum +1", augments={'Path: A',}},
    body={ name="Telchine Chas.", augments={'Enh. Mag. eff. dur. +10',}},
    sub="Wind Knife",
    sub="Firetongue",
    main="Lament",
    left_ring="Stikini Ring +1",
    body="Foire Tobe +3",
    back={ name="Visucius's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    body="Tali'ah Manteel +2",
    back={ name="Lugh's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Haste+10','Phys. dmg. taken-10%',}},
    feet="Aya. Gambieras +2",
    main="Sha Wujing's Lance",
    waist="Ukko Sash",
    back={ name="Visucius's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Accuracy+20 Attack+20','Pet: Accuracy+10 Pet: Rng. Acc.+10','Pet: Haste+10','System: 1 ID: 1247 Val: 4',}},
    back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Phys. dmg. taken-10%',}},
    hands={ name="Herculean Gloves", augments={'"Conserve MP"+1','Accuracy+21','"Treasure Hunter"+2',}},
    hands={ name="Telchine Gloves", augments={'Enh. Mag. eff. dur. +10',}},
    back="Argocham. Mantle",
    left_ear="Rimeice Earring",
    hands="Aya. Manopolas +2",
    legs={ name="Samnuha Tights", augments={'STR+9','DEX+8','"Dbl.Atk."+2','"Triple Atk."+2',}},
    legs={ name="Amalric Slops +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    main="Melon Slicer",
    body="Ayanmo Corazza +2",
    ammo="Charis Feather",
    left_ring="Varar Ring +1",
    back={ name="Lugh's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    neck="Voltsurge Torque",
    legs={ name="Telchine Braconi", augments={'Enh. Mag. eff. dur. +10',}},
    ammo="Yetshila +1",
    main="Ranine Staff",
    left_ear="Etiolation Earring",
    left_ear={ name="Skulk. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+11','Mag. Acc.+11','"Store TP"+3',}},
    waist="Luminary Sash",
    main={ name="Musa", augments={'Path: C',}},
    left_ring="Overbearing Ring",
    head="Aya. Zucchetto +2",
    head="Kara. Cappello +1",
    sub={ name="Asclepius", augments={'Path: C',}},
    left_ring="Epona's Ring",
    legs="Kara. Pantaloni +1",
    head={ name="Adhemar Bonnet +1", augments={'STR+12','DEX+12','Attack+20',}},
    body="Malignance Tabard",
    back={ name="Lugh's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    left_ring="Defending Ring",
    feet={ name="Telchine Pigaches", augments={'Enh. Mag. eff. dur. +10',}},
    ammo="Seraphic Ampulla",
    waist="Reiki Yotai",
    hands={ name="Chironic Gloves", augments={'"Fast Cast"+7','MND+9','Mag. Acc.+4','"Mag.Atk.Bns."+13',}},
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    legs="Aya. Cosciales +2",
    back={ name="Mending Cape", augments={'Healing magic skill +10','Enha.mag. skill +10','Mag. Acc.+7','"Cure" potency +3%',}},
    head="Theophany Cap +2",
    feet={ name="Chironic Slippers", augments={'Mag. Acc.+21','"Fast Cast"+7','MND+9',}},
    legs={ name="Chironic Hose", augments={'Mag. Acc.+21 "Mag.Atk.Bns."+21','"Fast Cast"+5','MND+11','Mag. Acc.+13','"Mag.Atk.Bns."+6',}},
    ammo="Homiliary",
    back={ name="Alaunus's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','"Fast Cast"+10','Phys. dmg. taken-10%',}},
    left_ring="Mujin Band",
    back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    left_ear="Mendi. Earring",
    left_ring="Inyanga Ring",
    waist="Hachirin-no-Obi",
    body={ name="Cohort Cloak +1", augments={'Path: A',}},
    sub="Enki Strap",
    hands={ name="Amalric Gages +1", augments={'INT+12','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    feet={ name="Herculean Boots", augments={'Weapon skill damage +4%','"Mag.Atk.Bns."+28','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    left_ring="Hetairoi Ring",
    sub="Bolelabunga",
    hands="Macu. Bangles +3",
    left_ring="Tali'ah Ring",
    waist="Moonbow Belt +1",
    left_ring="Regal Ring",
    legs="Hiza. Hizayoroi +2",
    left_ear="Sherida Earring",
    legs="Dashing Subligar",
    left_ear="Burana Earring",
    left_ear="Eabani Earring",
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    hands="Pinga Mittens +1",
    legs="Pinga Pants +1",
    main="Khatvanga",
    body={ name="Amalric Doublet +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    feet={ name="Amalric Nails +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    body="Karagoz Farsetto",
    hands={ name="Adhemar Wrist. +1", augments={'STR+12','DEX+12','Attack+20',}},
    legs="Skulk. Culottes +2",
    feet={ name="Herculean Boots", augments={'Accuracy+20 Attack+20','Crit. hit damage +4%','STR+8',}},
    back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    back={ name="Toetapper Mantle", augments={'"Store TP"+2','"Dual Wield"+2','"Rev. Flourish"+30',}},
    feet="Pinga Pumps +1",
    legs={ name="Ryuo Hakama +1", augments={'Accuracy+25','"Store TP"+5','Phys. dmg. taken -4',}},
    neck={ name="Clr. Torque +1", augments={'Path: A',}},
    head={ name="Kaykaus Mitra +1", augments={'MP+80','Spell interruption rate down +12%','"Cure" spellcasting time -7%',}},
    neck={ name="Etoile Gorget +2", augments={'Path: A',}},
    left_ear="Brutal Earring",
    body="Nukumi Gausape +3",
    feet={ name="Kaykaus Boots +1", augments={'Mag. Acc.+20','"Cure" potency +6%','"Fast Cast"+4',}},
    feet={ name="Herculean Boots", augments={'"Triple Atk."+3','Rng.Atk.+13','Quadruple Attack +3','Accuracy+13 Attack+13','Mag. Acc.+4 "Mag.Atk.Bns."+4',}},
    left_ear="Domes. Earring",
    left_ring="C. Palug Ring",
    left_ear="Odr Earring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Haste+10','Mag. Evasion+15',}},
    neck="Saevus Pendant +1",
    back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10','Phys. dmg. taken-10%',}},
    waist="Windbuffet Belt +1",
    body="Skulker's Vest +2",
    body="Pinga Tunic +1",
    back={ name="Alaunus's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    neck="Warder's Charm +1",
    ammo="Yamarang",
    left_ring="Gere Ring",
    hands={ name="Merlinic Dastanas", augments={'"Occult Acumen"+11','INT+10','Mag. Acc.+6',}},
    sub={ name="Bunzi's Rod", augments={'Path: A',}},
    head="Pinga Crown +1",
    main={ name="Kaumodaki", augments={'Path: C',}},
    body={ name="Horos Casaque +3", augments={'Enhances "No Foot Rise" effect',}},
    hands={ name="Pitre Dastanas +3", augments={'Enhances "Fine-Tuning" effect',}},
    left_ring="Chirich Ring +1",
    back={ name="Alaunus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    hands={ name="Fanatic Gloves", augments={'MP+50','Healing magic skill +10','"Conserve MP"+7','"Fast Cast"+7',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    body="Mallquis Saio +2",
    hands="Skulk. Armlets +1",
    left_ear="Lugalbanda Earring",
    left_ring="Niqmaddu Ring",
    waist="Fucho-no-Obi",
    left_ring="Petrov Ring",
    feet="Tandava Crackows",
    body="Seidr Cotehardie",
    body="Udug Jacket",
    ammo="Staunch Tathlum +1",
    head={ name="Anwig Salade", augments={'Attack+3','Pet: Damage taken -10%','Attack+3','Pet: "Regen"+1',}},
    head="Pixie Hairpin +1",
    left_ear="Cessance Earring",
    left_ring="Archon Ring",
    sub={ name="Rostam", augments={'Path: A',}},
    ammo="Impatiens",
    waist="Witful Belt",
    feet={ name="Merlinic Crackows", augments={'Attack+22','"Fast Cast"+7',}},
    feet={ name="Merlinic Crackows", augments={'"Mag.Atk.Bns."+2','"Occult Acumen"+11','MND+9','Mag. Acc.+15',}},
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+22','"Occult Acumen"+11','INT+9',}},
    head={ name="Merlinic Hood", augments={'"Fast Cast"+7','"Mag.Atk.Bns."+14',}},
    left_ring="Evanescence Ring",
    head="Mall. Chapeau +2",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10','Phys. dmg. taken-10%',}},
    feet="Arbatel Loafers +3",
    head={ name="Ryuo Somen +1", augments={'HP+65','"Store TP"+5','"Subtle Blow"+8',}},
    left_ear="Ishvara Earring",
    sub={ name="Makhila +2", augments={'TP Bonus +1000',}},
    ammo="Leisure Musk +1",
    left_ear="Glorious Earring",
    ammo={ name="Coiste Bodhar", augments={'Path: A',}},
    ammo={ name="Seeth. Bomblet +1", augments={'Path: A',}},
    ammo="Crepuscular Pebble",
    head="Pill. Bonnet +3",
    head={ name="Plun. Bonnet +3", augments={'Enhances "Aura Steal" effect',}},
    body="Pillager's Vest +3",
    body={ name="Plunderer's Vest +3", augments={'Enhances "Ambush" effect',}},
    hands="Meg. Gloves +2",
    legs="Pill. Culottes +3",
    legs={ name="Plun. Culottes +3", augments={'Enhances "Feint" effect',}},
    feet="Pill. Poulaines +3",
    feet={ name="Plun. Poulaines +3", augments={'Enhances "Assassin\'s Charge" effect',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Toutatis's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    left_ear="Friomisi Earring",
    left_ear="Crematio Earring",
    left_ring="Dingir Ring",
    neck={ name="Asn. Gorget +2", augments={'Path: A',}},
    neck="Sanctity Necklace",
    sub={ name="Fusetto +2", augments={'TP Bonus +1000',}},
    sub="Naegling",
    head={ name="Blistering Sallet +1", augments={'Path: A',}},
    hands={ name="Gazu Bracelets +1", augments={'Path: A',}},
    feet={ name="Gleti's Boots", augments={'Path: A',}},
    range={ name="Neo Animator", augments={'Path: A',}},
    head={ name="Mpaca's Cap", augments={'Path: A',}},
    body={ name="Mpaca's Doublet", augments={'Path: A',}},
    hands={ name="Mpaca's Gloves", augments={'Path: A',}},
    back={ name="Visucius's Mantle", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Senuna's Mantle", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    left_ear={ name="Schere Earring", augments={'Path: A',}},
    sub={ name="Twashtar", augments={'Path: A',}},
    left_ring="Eshmun's Ring",
    neck="Nicander's Necklace",
    left_ear="Infused Earring",
    body={ name="Gleti's Cuirass", augments={'Path: A',}},
    sub="Kaja Knife",
    legs={ name="Mpaca's Hose", augments={'Path: A',}},
    feet={ name="Mpaca's Boots", augments={'Path: A',}},
    hands={ name="Gleti's Gauntlets", augments={'Path: A',}},
    hands={ name="Plun. Armlets +1", augments={'Enhances "Perfect Dodge" effect',}},
    neck="Rep. Plat. Medal",
    legs={ name="Gleti's Breeches", augments={'Path: A',}},
    head={ name="Gleti's Mask", augments={'Path: A',}},
    feet="Macu. Toe Sh. +3",
    ammo="Voluspa Tathlum",
    sub="Dolichenus",
    sub={ name="Kumbhakarna", augments={'Pet: "Mag.Atk.Bns."+19','Pet: TP Bonus+200',}},
    sub={ name="Kumbhakarna", augments={'Pet: Attack+19 Pet: Rng.Atk.+19','Pet: TP Bonus+200',}},
    left_ear="Mache Earring +1",
    sub="Agwu's Axe",
    sub="Sacro Bulwark",
    head={ name="Ankusa Helm +3", augments={'Enhances "Killer Instinct" effect',}},
    head={ name="Emicho Coronet +1", augments={'Pet: Accuracy+20','Pet: Attack+20','Pet: "Dbl. Atk."+4',}},
    head="Totemic Helm +1",
    body={ name="Taeon Tabard", augments={'Pet: Mag. Evasion+22','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    legs={ name="Ankusa Trousers +1", augments={'Enhances "Familiar" effect',}},
    feet={ name="Taeon Boots", augments={'Pet: Mag. Evasion+24','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    feet={ name="Emi. Gambieras +1", augments={'Pet: Accuracy+20','Pet: Attack+20','Pet: "Dbl. Atk."+4',}},
    feet={ name="Valorous Greaves", augments={'Pet: "Mag.Atk.Bns."+29','Pet: INT+13','Pet: Accuracy+4 Pet: Rng. Acc.+4','Pet: Attack+10 Pet: Rng.Atk.+10',}},
    feet="Tot. Gaiters +1",
    neck="Adad Amulet",
    body="Tot. Jackcoat +3",
    waist="Svelt. Gouriz +1",
    neck={ name="Bathy Choker +1", augments={'Path: A',}},
    sub="Ceremonial Dagger",
    back={ name="Senuna's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    feet={ name="Agwu's Pigaches", augments={'Path: A',}},
    legs={ name="Agwu's Slops", augments={'Path: A',}},
    hands={ name="Agwu's Gages", augments={'Path: A',}},
    body={ name="Agwu's Robe", augments={'Path: A',}},
    head={ name="Agwu's Cap", augments={'Path: A',}},
    feet="Hiza. Sune-Ate +2",
    back={ name="Sucellos's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Aurist's Cape +1", augments={'Path: A',}},
    left_ear="Sanare Earring",
    left_ear="Crep. Earring",
    range={ name="Fomalhaut", augments={'Path: A',}},
    body="Crepuscular Cloak",
    feet="Thereoid Greaves",
    legs="Leth. Fuseau +3",
    neck={ name="Dls. Torque +2", augments={'Path: A',}},
    sub={ name="Crocea Mors", augments={'Path: C',}},
    ammo="Amar Cluster",
    main="Hvergelmir",
    range="Ullr",
    left_ring="Moonlight Ring",
    head="Atrophy Chapeau +3",
    head={ name="Viti. Chapeau +3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    legs="Ea Slops +1",
    feet="Leth. Houseaux +3",
    body="Atrophy Tabard +3",
    body={ name="Viti. Tabard +3", augments={'Enhances "Chainspell" effect',}},
    body="Ea Houppe. +1",
    hands="Leth. Ganth. +3",
    hands="Atrophy Gloves +3",
    hands={ name="Viti. Gloves +3", augments={'Enhancing Magic duration',}},
    head="Leth. Chappel +1",
    hands={ name="Kaykaus Cuffs +1", augments={'MP+80','MND+12','Mag. Acc.+20',}},
    legs="Atrophy Tights +3",
    head="Ea Hat +1",
    left_ear={ name="Leth. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+14','Mag. Acc.+14','"Dbl.Atk."+5',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet={ name="Vitiation Boots +3", augments={'Immunobreak Chance',}},
    waist={ name="Obstin. Sash", augments={'Path: A',}},
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    back={ name="Sucellos's Cape", augments={'MND+20','Accuracy+20 Attack+20','MND+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Lugh's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Lugh's Cape", augments={'MP+60','MP+20','"Fast Cast"+10','Phys. dmg. taken-10%',}},
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +7','Enha.mag. skill +7','Mag. Acc.+6','Enh. Mag. eff. dur. +19',}},
    left_ear="Vor Earring",
    left_ear="Snotra Earring",
    left_ring="Mephitas's Ring",
    feet={ name="Bunzi's Sabots", augments={'Path: A',}},
    head={ name="Arch. Petasos +3", augments={'Increases Ancient Magic damage and magic burst damage',}},
    body={ name="Arch. Coat +3", augments={'Enhances "Manafont" effect',}},
    hands={ name="Arch. Gloves +3", augments={'Increases Elemental Magic accuracy',}},
    body="Spaekona's Coat +3",
    legs={ name="Arch. Tonban +3", augments={'Increases Elemental Magic debuff time and potency',}},
    feet={ name="Arch. Sabots +3", augments={'Increases Aspir absorption amount',}},
    neck={ name="Src. Stole +2", augments={'Path: A',}},
    back={ name="Taranus's Cape", augments={'MP+60','Mag. Acc+20 /Mag. Dmg.+20','MP+20','"Fast Cast"+10','Mag. Evasion+15',}},
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Phys. dmg. taken-10%',}},
    back={ name="Taranus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','"Fast Cast"+10','Mag. Evasion+15',}},
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+5','"Store TP"+10','Phys. dmg. taken-10%',}},
    left_ear="Barkaro. Earring",
    left_ring="Eshmun's Ring",
    waist="Gishdubar Sash",
    hands={ name="Bunzi's Gloves", augments={'Path: A',}},
    legs="Bunzi's Pants",
    body={ name="Bunzi's Robe", augments={'Path: A',}},
    head={ name="Bunzi's Hat", augments={'Path: A',}},
    head="Assim. Keffiyeh +3",
    legs="Assim. Shalwar +3",
    back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    legs="Wicce Chausses +2",
    back={ name="Taranus's Cape", augments={'INT+20','Accuracy+20 Attack+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Taranus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    neck="Elite Royal Collar",
    neck="Sibyl Scarf",
    left_ear={ name="Hashi. Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+16','Mag. Acc.+16','"Dbl.Atk."+6','STR+7 INT+7',}},
    head={ name="Valorous Mask", augments={'Pet: "Mag.Atk.Bns."+27','Pet: INT+14','Pet: Accuracy+12 Pet: Rng. Acc.+12','Pet: Attack+7 Pet: Rng.Atk.+7',}},
    head={ name="Taeon Chapeau", augments={'Pet: Mag. Evasion+24','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    body="Sacro Breastplate",
    left_ring="Rufescent Ring",
    waist="Chr. Bul. Pouch",
    sub={ name="Kumbhakarna", augments={'Pet: "Mag.Atk.Bns."+19','Pet: TP Bonus+200',}},
    feet="Wicce Sabots +2",
    hands={ name="Ankusa Gloves", augments={'Enhances "Beast Affinity" effect',}},
    main={ name="Mpaca's Staff", augments={'Path: A',}},
    hands={ name="Taeon Gloves", augments={'Pet: Mag. Evasion+24','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    hands="Nukumi Manoplas +3",
    hands="Tot. Gloves +1",
    legs={ name="Valorous Hose", augments={'Pet: "Mag.Atk.Bns."+28','Pet: Haste+3','Pet: INT+12','Pet: Accuracy+14 Pet: Rng. Acc.+14','Pet: Attack+13 Pet: Rng.Atk.+13',}},
    legs={ name="Taeon Tights", augments={'Pet: Mag. Evasion+23','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    legs="Tot. Trousers +1",
    legs={ name="Desultor Tassets", augments={'"Phantom Roll" ability delay -5','"Repair" potency +10%',}},
    left_ear={ name="Macu. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+14','Mag. Acc.+14','"Store TP"+5',}},
    head="Amalric Coif +1",
    head={ name="Luh. Keffiyeh +1", augments={'Enhances "Convergence" effect',}},
    head={ name="Taeon Chapeau", augments={'Phalanx +3',}},
    body={ name="Taeon Tabard", augments={'Spell interruption rate down -10%','Phalanx +3',}},
    body="Assim. Jubbah +1",
    hands="Assim. Bazu. +2",
    hands={ name="Taeon Gloves", augments={'Phalanx +3',}},
    legs={ name="Luhlaza Shalwar +3", augments={'Enhances "Assimilation" effect',}},
    legs={ name="Taeon Tights", augments={'Phalanx +3',}},
    head="Hashishin Kavuk +3",
    feet={ name="Luhlaza Charuqs +1", augments={'Enhances "Diffusion" effect',}},
    feet={ name="Taeon Boots", augments={'Phalanx +3',}},
    neck={ name="Mirage Stole +2", augments={'Path: A',}},
    waist="Emphatikos Rope",
    back={ name="Rosmerta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Phys. dmg. taken-10%',}},
    left_ear="Njordr Earring",
    body="Hashishin Mintan +3",
    waist="Yemaya Belt",
    body={ name="Luhlaza Jubbah +1", augments={'Enhances "Enchainment" effect',}},
    hands="Hashi. Bazu. +3",
    hands={ name="Luh. Bazubands +1", augments={'Enhances "Azure Lore" effect',}},
    legs="Hashishin Tayt +3",
    neck="Iskur Gorget",
    feet="Hashi. Basmak +3",
    feet="Assim. Charuqs +1",
    back={ name="Rosmerta's Cape", augments={'AGI+20','Eva.+20 /Mag. Eva.+20','Evasion+10','Enmity+10','Evasion+15',}},
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    left_ring="Sheltered Ring",
    left_ear="Digni. Earring",
    feet="Jhakri Pigaches +2",
    left_ear="Magnetic Earring",
    head={ name="Carmine Mask +1", augments={'Accuracy+20','Mag. Acc.+12','"Fast Cast"+4',}},
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    waist="Eschan Stone",
    neck="Quanpur Necklace",
    back={ name="Cornflower Cape", augments={'MP+17','DEX+4','Accuracy+1','Blue Magic skill +10',}},
    ammo="Hauksbok Bullet",
    left_ear="Tuisto Earring",
    sub="Gambanteinn",
    body={ name="Lanun Frac +3", augments={'Enhances "Loaded Deck" effect',}},
    left_ring="Crepuscular Ring",
    body="Chasseur's Frac +3",
    legs={ name="Adhemar Kecks +1", augments={'AGI+12','"Rapid Shot"+13','Enmity-6',}},
    feet="Meg. Jam. +2",
    head={ name="Taeon Chapeau", augments={'"Snapshot"+5','"Snapshot"+5',}},
    neck="Sroda Necklace",
    hands={ name="Lanun Gants +3", augments={'Enhances "Fold" effect',}},
    left_ring="Luzaf's Ring",
    head={ name="Lanun Tricorne +1", augments={'Enhances "Winning Streak" effect',}},
    head="Laksa. Tricorne +1",
    body="Laksa. Frac +3",
    hands="Laksa. Gants +1",
    legs={ name="Lanun Trews +1", augments={'Enhances "Snake Eye" effect',}},
    legs="Laksa. Trews +1",
    feet="Laksa. Bottes +1",
    range="Compensator",
    sub={ name="Rostam", augments={'Path: C',}},
    left_ring="Facility Ring",
    head="Skulker's Bonnet +2",
    feet="Skulk. Poulaines +2",
    main={ name="Godhands", augments={'Path: A',}},
    left_ring="Begrudging Ring",
    left_ring="Barataria Ring",
    range={ name="Anarchy +2", augments={'Delay:+60','TP Bonus +1000',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    back={ name="Camulus's Mantle", augments={'INT+20','Eva.+20 /Mag. Eva.+20','"Snapshot"+10','Mag. Evasion+15',}},
    back={ name="Camulus's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    back={ name="Camulus's Mantle", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    feet={ name="Lanun Bottes +3", augments={'Enhances "Wild Card" effect',}},
    neck="Regal Necklace",
    neck={ name="Comm. Charm +2", augments={'Path: A',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Rng.Acc.+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    waist="K. Kachina Belt +1",
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Crit.hit rate+10','Phys. dmg. taken-10%',}},
    range={ name="Death Penalty", augments={'Path: A',}},
    left_ring="Hajduk Ring +1",
    left_ear="Beyla Earring",
    sub="Nusku Shield",
    hands={ name="Carmine Fin. Ga. +1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    sub={ name="Rostam", augments={'Path: B',}},
    feet="Osh. Leggings +1",
    head="Oshosi Mask +1",
    legs="Osh. Trousers +1",
    body="Meg. Cuirie +2",
    hands="Mummu Wrists +2",
    head="Meghanada Visor +2",
    left_ring="Mummu Ring",
    legs="Darraigner's Brais",
    feet={ name="Pursuer's Gaiters", augments={'Rng.Acc.+10','"Rapid Shot"+10','"Recycle"+15',}},
    range={ name="Armageddon", augments={'Path: A',}},
    waist="Dev. Bul. Pouch",
    waist="Liv. Bul. Pouch",
    legs={ name="Merlinic Shalwar", augments={'AGI+5','Pet: STR+2','"Treasure Hunter"+2','Mag. Acc.+3 "Mag.Atk.Bns."+3',}},
    feet={ name="Taeon Boots", augments={'Pet: Accuracy+21 Pet: Rng. Acc.+21','Pet: "Dbl. Atk."+5','Pet: Damage taken -4%',}},
    hands={ name="Taeon Gloves", augments={'Pet: Accuracy+23 Pet: Rng. Acc.+23','Pet: "Dbl. Atk."+5','Pet: Damage taken -4%',}},
    legs="Nukumi Quijotes +3",
    head="Chass. Tricorne +3",
    main={ name="Kenkonken", augments={'Path: A',}},
    sub={ name="Ikenga's Axe", augments={'Path: A',}},
    ammo="Regal Gem",
    left_ear={ name="Ebers Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+16','Mag. Acc.+16','Damage taken-6%','STR+7 MND+7',}},
    head="Wicce Petasos +2",
    ammo="Oshasha's Treatise",
    body={ name="Ikenga's Vest", augments={'Path: A',}},
    hands="Chasseur's Gants +3",
    head={ name="Ikenga's Hat", augments={'Path: A',}},
    hands={ name="Ikenga's Gloves", augments={'Path: A',}},
    feet={ name="Ikenga's Clogs", augments={'Path: A',}},
    legs={ name="Ikenga's Trousers", augments={'Path: A',}},
    legs="Chas. Culottes +3",
    hands="Wicce Gloves +2",
    feet="Chass. Bottes +3",
    left_ring="Moonlight Ring",
    ammo="Sroda Tathlum",
    left_ear={ name="Kara. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+14','Mag. Acc.+14','"Store TP"+5',}},
    sub={ name="Sakpata's Sword", augments={'Path: A',}},
    body="Nisroch Jerkin",
    main="Karambit",
    sub="Raetic Rod +1",
    body="Arbatel Gown +3",
    legs="Arbatel Pants +3",
    waist="Orpheus's Sash",
    left_ring="Epaminondas's Ring",
    left_ring="Sroda Ring",
    sub="Crepuscular Knife",
    head="Stout Bonnet",
    head="Nuk. Cabasset +2",
    sub={ name="Aymur", augments={'Path: A',}},
    feet="Nukumi Ocreae +3",
    left_ear="Sroda Earring",
    back={ name="Artio's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Eva.+20 /Mag. Eva.+20','Pet: Attack+10 Pet: Rng.Atk.+10','Pet: "Regen"+10','Pet: Damage taken -5%',}},
    back={ name="Artio's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    back={ name="Artio's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    back={ name="Artio's Mantle", augments={'CHR+20','Mag. Acc+20 /Mag. Dmg.+20','CHR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    back={ name="Artio's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    left_ear="Thrud Earring",
    body="Crepuscular Mail",
    head="Crepuscular Helm",
    neck={ name="Bst. Collar +2", augments={'Path: A',}},
    neck="Melic Torque",
    item="Dial Key #Ab",
    item="Blk. Tiger Fang",
    item="Ifritite",
    item="Titanite",
    item="Soil Geode",
    item="Flame Geode",
    item="H.Q. B. Tiger Hide",
    item="Ardor Coin",
    item="Ardor Stone",
    waist="Light Belt",
}